[package]
name = "inverted_index"
version = "0.1.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]

[dependencies]
lazy_static = "*"
regex = "*"
libc = "*"

[lib]
name = "index"
crate-type = ["dylib"]
